### ISSUE TITLE
Nice Work

### ISSUE THREAD

**Issue by fidodone** [Tenpi/Crunchyroll-Downloader-GUI#1]
I came to thank you for the excellent tool
And I would like to know if in the future would have the possibility to add options to select the language of the subtitle

Go ahead with the excellent work

**Comment by Tenpi** [comment]
Yeah, sure. Sorry, I assumed that people would only be interested in the English sub/dub. I will let you know when I implement this.

**Comment by Tenpi** [comment]
Ok, you can select a different language for either subtitles or dubs starting on `v0.0.8`. You can also download without any subtitles by choosing `Japanese Dub`. 

Some other changes are that downloading a premium episode without a premium account will download the preview instead of posting an error message, and that you can now pick `360p` and `240p` for the quality. 

Let me know if there are any issues.
